// 球队英文->中文映射
// 自动生成
module.exports = {
  "Tottenham": "热刺",
  "Arsenal": "阿森纳",
  "Chelsea": "切尔西",
  "Liverpool": "利物浦",
  "Manchester City": "曼城",
  "Manchester Utd": "曼联",
  "Manchester United": "曼联",
  "Newcastle": "纽卡斯尔",
  "Aston Villa": "阿斯顿维拉",
  "West Ham": "西汉姆",
  "Brighton": "布莱顿",
  "Wolves": "狼队",
  "Fulham": "富勒姆",
  "Crystal Palace": "水晶宫",
  "Brentford": "布伦特福德",
  "Everton": "埃弗顿",
  "Nottingham Forest": "诺丁汉森林",
  "Bournemouth": "伯恩茅斯",
  "Leicester": "莱斯特城",
  "Leeds": "利兹联",
  "Burnley": "伯恩利",
  "Sunderland": "桑德兰",
  "Ipswich": "伊普斯维奇",
  "Southampton": "南安普顿",
  "Norwich": "诺维奇",
  "Real Madrid": "皇马",
  "Barcelona": "巴萨",
  "Atletico Madrid": "马竞",
  "Atlético Madrid": "马竞",
  "Sevilla": "塞维利亚",
  "Real Sociedad": "皇家社会",
  "Real Betis": "皇家贝蒂斯",
  "Betis": "贝蒂斯",
  "Villarreal": "比利亚雷亚尔",
  "Athletic Bilbao": "毕尔巴鄂",
  "Valencia": "瓦伦西亚",
  "Osasuna": "奥萨苏纳",
  "Celta Vigo": "塞尔塔",
  "Getafe": "赫塔菲",
  "Alaves": "阿拉维斯",
  "Espanyol": "西班牙人",
  "Mallorca": "马洛卡",
  "Girona": "赫罗纳",
  "Las Palmas": "拉斯帕尔马斯",
  "Rayo Vallecano": "巴列卡诺",
  "Leganes": "莱加内斯",
  "Oviedo": "奥维耶多",
  "Inter": "国米",
  "Inter Milan": "国米",
  "AC Milan": "AC米兰",
  "Milan": "AC米兰",
  "Juventus": "尤文",
  "Napoli": "那不勒斯",
  "Atalanta": "亚特兰大",
  "Lazio": "拉齐奥",
  "AS Roma": "罗马",
  "Roma": "罗马",
  "Fiorentina": "佛罗伦萨",
  "Bologna": "博洛尼亚",
  "Torino": "都灵",
  "Udinese": "乌迪内斯",
  "Monza": "蒙扎",
  "Genoa": "热那亚",
  "Lecce": "莱切",
  "Empoli": "恩波利",
  "Cagliari": "卡利亚里",
  "Como": "科莫",
  "Parma": "帕尔马",
  "Verona": "维罗纳",
  "Cremonese": "克雷莫纳",
  "Sassuolo": "萨索洛",
  "Bayern Munich": "拜仁",
  "Borussia Dortmund": "多特蒙德",
  "Dortmund": "多特蒙德",
  "Bayer Leverkusen": "勒沃库森",
  "RB Leipzig": "莱比锡",
  "Leipzig": "莱比锡",
  "Eintracht Frankfurt": "法兰克福",
  "Frankfurt": "法兰克福",
  "Borussia M'gladbach": "门兴",
  "Borussia M.Gladbach": "门兴",
  "Mönchengladbach": "门兴",
  "VfB Stuttgart": "斯图加特",
  "VfL Wolfsburg": "沃尔夫斯堡",
  "Wolfsburg": "沃尔夫斯堡",
  "Union Berlin": "柏林联合",
  "SC Freiburg": "弗赖堡",
  "Freiburg": "弗赖堡",
  "Mainz": "美因茨",
  "FC Augsburg": "奥格斯堡",
  "Augsburg": "奥格斯堡",
  "TSG Hoffenheim": "霍芬海姆",
  "Hoffenheim": "霍芬海姆",
  "Werder Bremen": "不莱梅",
  "FC Heidenheim": "海登海姆",
  "Heidenheim": "海登海姆",
  "FC St. Pauli": "圣保利",
  "Holstein Kiel": "荷尔斯泰因基尔",
  "PSG": "巴黎",
  "Paris Saint Germain": "巴黎圣日耳曼",
  "Paris Saint-Germain": "巴黎圣日耳曼",
  "Marseille": "马赛",
  "Olympique Marseille": "马赛",
  "Lyon": "里昂",
  "Olympique Lyonnais": "里昂",
  "Monaco": "摩纳哥",
  "Lille": "里尔",
  "LOSC Lille": "里尔",
  "Nice": "尼斯",
  "Lens": "朗斯",
  "Rennes": "雷恩",
  "Stade Rennais": "雷恩",
  "Strasbourg": "斯特拉斯堡",
  "Nantes": "南特",
  "Montpellier": "蒙彼利埃",
  "Reims": "兰斯",
  "Toulouse": "图卢兹",
  "Brest": "布雷斯特",
  "Brestois": "布雷斯特",
  "Auxerre": "欧塞尔",
  "Le Havre": "勒阿弗尔",
  "Angers": "昂热",
  "Saint-Étienne": "圣埃蒂安",
  "HJK Helsinki": "赫尔辛基",
  "Lahti": "拉赫蒂",
  "Cukaricki": "库卡里奇",
  "FK Crvena Zvezda": "贝尔格莱德红星",
  "Club Deportivo Los Chankas": "洛斯香卡斯",
  "Deportivo Garcilaso": "加西拉索",
  "Ural": "乌拉尔",
  "Shinnik Yaroslavl": "辛历克",
  "Sligo Rovers": "斯莱戈流浪",
  "St Patrick's Athl.": "圣帕特里克",
  "Waterford": "沃特福德联",
  "Dundalk": "邓多克",
  "Heart Of Midlothian": "哈茨",
  "Rangers": "格拉斯哥流浪者",
  "Bodo/Glimt": "博德闪耀",
  "Molde": "莫尔德",
  "Lask Linz": "LASK林茨",
  "Rapid Vienna": "维也纳快速",
  "Odisha": "奥迪萨",
  "Bengaluru": "邦加罗尔",
  "Istra 1961": "依斯特拉",
  "NK Slaven Belupo": "比路朴",
  "Al-Fayha": "费哈",
  "Al Riyadh": "利雅得体育",
  "Radomiak Radom": "拉多麦科",
  "Lechia Gdansk": "列治亚",
  "Al-Ittihad FC": "吉达联合",
  "Al Kholood": "拉斯永恒",
  "Almeria": "阿尔梅里亚",
  "Mirandes": "米兰德斯",
  "Sporting CP": "葡萄牙体育",
  "Guimaraes": "吉马良斯",
  "Radnik Surdulica": "苏杜利察",
  "Vojvodina": "沃伊沃迪纳",
  "Penarol": "佩纳罗尔",
  "Defensor Sporting": "防卫者体育"
};
